// AI daily brief — one short morning paragraph from today's weather +
// calendar, generated by Claude. One API call per local day (date-keyed
// cache; a Railway redeploy costs at most one extra call). Env-gated on
// ANTHROPIC_API_KEY — without it the widget shows its setup card.
const Anthropic = require('@anthropic-ai/sdk');
const status = require('./_status');

// Haiku by default — the user-approved cost profile is "pennies/month"
// (one small call per day). Override with BRIEF_MODEL if quality ever
// matters more than cost here.
const MODEL = process.env.BRIEF_MODEL || 'claude-haiku-4-5';

let _client = null;
function client() {
  if (!process.env.ANTHROPIC_API_KEY) return null;
  if (!_client) _client = new Anthropic(); // reads ANTHROPIC_API_KEY
  return _client;
}

let cache = null; // { dayKey, text, at }

function localDayKey(tz) {
  try {
    return new Intl.DateTimeFormat('sv-SE', {
      timeZone: tz || 'UTC', year: 'numeric', month: '2-digit', day: '2-digit'
    }).format(new Date());
  } catch {
    return new Date().toDateString();
  }
}

// Compact, deterministic-ish context so the prompt stays small.
function buildContext({ cfg, weather, events }) {
  const parts = [];
  if (weather && weather.desc && weather.desc !== 'NO DATA') {
    parts.push(`Weather: ${weather.desc}, currently ${weather.temp}°, high ${weather.tempMax}°, low ${weather.tempMin}°.`);
    if (Number.isFinite(weather.rainInMin)) parts.push(`Rain expected in about ${weather.rainInMin} minutes.`);
  }
  const tz = (cfg && cfg.timezone) || 'UTC';
  const today = localDayKey(tz);
  const dayOf = (iso) => {
    try {
      return new Intl.DateTimeFormat('sv-SE', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' })
        .format(new Date(iso));
    } catch { return ''; }
  };
  const todays = (Array.isArray(events) ? events : [])
    .filter(e => e.startISO && dayOf(e.startISO) === today)
    .slice(0, 8)
    .map(e => `- ${e.title}${e.isAllDay ? ' (all day)' : e.startLabel ? ` at ${e.startLabel}` : ''}`);
  if (todays.length) parts.push(`Today's calendar:\n${todays.join('\n')}`);
  else parts.push('No calendar events today.');
  return parts.join('\n');
}

async function fetchBrief({ cfg, weather, events }) {
  const c = client();
  if (!c) return null; // no key — renderer shows setup state
  const tz = (cfg && cfg.timezone) || 'UTC';
  const dayKey = localDayKey(tz);
  if (cache && cache.dayKey === dayKey) { status.cacheHit('brief'); return cache; }

  const t0 = Date.now();
  try {
    const response = await c.messages.create({
      model: MODEL,
      max_tokens: 300,
      system: 'You write a two-to-three sentence morning brief for a small e-ink dashboard. '
        + 'Plain text only — no markdown, no emoji, no greetings like "Good morning". '
        + 'Weave the weather and the day\'s schedule into something a person glances at once over coffee. '
        + 'Dry wit welcome; padding is not.',
      messages: [{ role: 'user', content: buildContext({ cfg, weather, events }) }],
    });
    const text = response.content
      .filter(b => b.type === 'text')
      .map(b => b.text)
      .join(' ')
      .trim();
    if (!text) throw new Error('empty completion');
    cache = { dayKey, text, at: Date.now(), stale: false };
    status.record('brief', { ok: true, ms: Date.now() - t0 });
    return cache;
  } catch (err) {
    status.record('brief', { ok: false, ms: Date.now() - t0, err: err.message || String(err) });
    if (cache) return { ...cache, stale: true };
    return null;
  }
}

module.exports = { fetchBrief };
