// Demo data used by the widget pool / hover-card preview. Each
// pool tile renders with this instead of the live config so users see
// what a fully-configured widget will look like, not the
// SETUP NEEDED placeholder. The numbers/copy are deliberately
// generic ("Coffee with Lia", AAPL, partly cloudy 82°F) so nothing
// reads like a real user's data — and they're frozen, not derived
// from the current date, so the pool preview is reproducible.

export const DEMO_WEATHER = {
  temp: 82, feelsLike: 86, tempMin: 68, tempMax: 90,
  humidity: 64,
  windSpeed: 7, windGust: 11, windDir: 'NW', windUnit: 'mph',
  cloudCover: 38,
  desc: 'PARTLY CLOUDY', main: 'Clouds',
  sunrise: '6:24',  sunset:  '8:22',
  sunriseMin: 384,  sunsetMin: 1222,  nowMin: 700,
  forecast: [
    { name: 'MON', hi: 82, lo: 68, main: 'Clouds', precip: 20 },
    { name: 'TUE', hi: 79, lo: 67, main: 'Rain',   precip: 70 },
    { name: 'WED', hi: 77, lo: 65, main: 'Rain',   precip: 80 },
    { name: 'THU', hi: 80, lo: 66, main: 'Clear',  precip:  5 },
    { name: 'FRI', hi: 84, lo: 69, main: 'Clear',  precip:  0 },
    { name: 'SAT', hi: 88, lo: 71, main: 'Clouds', precip: 15 },
    { name: 'SUN', hi: 85, lo: 70, main: 'Clouds', precip: 30 }
  ],
  hourly: [
    { label: '9P',  temp: 78, main: 'Clear', precip:  5 },
    { label: '10P', temp: 76, main: 'Clear', precip:  5 },
    { label: '11P', temp: 74, main: 'Clear', precip:  5 },
    { label: '12A', temp: 72, main: 'Clouds', precip: 10 },
    { label: '1A',  temp: 71, main: 'Clouds', precip: 15 },
    { label: '2A',  temp: 70, main: 'Rain',   precip: 60 }
  ],
  stale: false,
  units: 'F'
};

export const DEMO_EVENTS = [
  { title: 'Coffee with Lia',       dayLabel: 'MON', startLabel: '9:00 AM',  section: 'TODAY' },
  { title: 'Brand workshop',        dayLabel: 'MON', startLabel: '12:30 PM', section: 'TODAY' },
  { title: 'Standup',               dayLabel: 'TUE', startLabel: '10:00 AM', section: 'LATER' },
  { title: 'Dentist',               dayLabel: 'WED', startLabel: '3:00 PM',  section: 'LATER' },
  { title: 'Yoga',                  dayLabel: 'THU', startLabel: '7:00 AM',  section: 'LATER' },
  { title: "Mom's birthday",        dayLabel: 'FRI', startLabel: 'all day',  section: 'LATER', isAllDay: true },
  { title: 'Dinner · 11 Madison',   dayLabel: 'SAT', startLabel: '7:30 PM',  section: 'LATER' },
  { title: 'Market run',            dayLabel: 'SUN', startLabel: '11:00 AM', section: 'LATER' }
];

// Placeholder demo image: 160×160 PNG, nested rotated-diamond pattern.
// Survives the 1-bit threshold (pure black/white only, no gray) so it
// reads cleanly at any popup scale. Generated by a sharp pipeline in
// the pool-demo helper; embedded here as a base64 string so the pool
// doesn't need to make a network call to populate the preview.
const DEMO_ARTWORK_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAKAAAACgAQMAAACxAfVuAAAABlBMVEX///8AAABVwtN+AAAACXBIWXMAAAPoAAAD6AG1e1JrAAACSklEQVR4nL3XTbKrIBCG4aYYMGQJLIWlmaW5FJfA0EHKPtX8GIV3eOs6ExN5ok3zReT/Hx8YczsM+gMGQ4HBeMJg+sJgvmBwUxhUXaFOdYV61RUaVFdoVF2hSXWFZtUVuqmuUNUV6mxwX5krNNhgWZnbAk165QWa9ZsW6KZnXKCqJcxQp3r4GWoDdmFmfuwWM7NOJhOzsmRi9iuPo34zTlDV4vYJahq3T1A7DWWC2hdDmaA2RTwnqGHyNUHtLF8T1L636QS1GWwufUArU/UNtROrT/eEVma7RXkzrT63B9QotT7zA1qZVp/pAW3Mdo+Jub2gjXnlF7Qxv+kFbcwzvqCNWcIL2piHf0Ebc3cvaGNaLckP2ph28XNDO9Nus9/QzrQJjxvamUYrN7QzpV4Z0MF8QTvT19kGtDNrLcmAdmatpU+HDmZqN2nQway1dHToYNZaKh06mPe1c9TmqKWrQwdzzKfXgzlkqn0J/Wppr9DBrGWTO7QuoV8tlQr9MW9a4U86uqfQ7ILOTL8o0W+P9JQCPU9PT97ROxJ6m4LvPVOFJKqlSFUXqD49VbKjmhdaHYLrKNOKS7Q2I63iQOvdU2dw1EOEuo1gX8rUwRL1ukhdMVD/9NRpHfVkoe4t2Ocz7QiJ9o5Iu0yg/cjTzuVojxPaDQX3zUw7bKK9ONKuHWh/95QEHGUGoXQhmEMyJZZE2SZSCgqUlzwlK0cZTCitCea6TAkwUVaMlCoD5U9PSdVRphVKv4I5GRM1Zm9M6ZjnMfnjfwT8N/Hvjj/llOftknBIkAAAAABJRU5ErkJggg==';

export const DEMO_AQI = {
  aqi: 42, band: 0, bands: 6, label: 'GOOD',
  pm25: 9, pm10: 17, o3: 31, no2: 8, stale: false
};

export const DEMO_CLOCK = {
  timeStr: '9:18',
  ampm: 'PM',
  dateLine: 'FRI MAY 31',
  style: 'big'
};

// A year of plausible contribution activity (Sun-aligned), for the code
// activity heatmap in the matrix / visual-regression.
export const DEMO_CODE_ACTIVITY = (() => {
  const days = [];
  const start = Date.UTC(2025, 5, 29); // a Sunday
  for (let i = 0; i < 371; i++) {
    // weekdays busier than weekends; a couple of quiet stretches.
    const dow = i % 7;
    const wk = Math.floor(i / 7);
    const busy = (dow >= 1 && dow <= 5) ? 1 : 0;
    const lull = (wk % 9 === 0) ? 0 : 1;
    const count = busy * lull * ((i * 7 + 3) % 6);
    const level = count === 0 ? 0 : count < 2 ? 1 : count < 4 ? 2 : count < 6 ? 3 : 4;
    days.push({ date: new Date(start + i * 86400000).toISOString().slice(0, 10), count, level });
  }
  return { user: 'octocat', days, total: days.reduce((s, d) => s + d.count, 0), stale: false };
})();

// Returns a render context for the given widget id with demo data
// plumbed into the slots the widget expects. cellW + cellH come from
// the size the pool is rendering at so widgets that branch on tier
// (forecast day count, hi-tier-only hourly strip, etc.) render at
// the size's actual fidelity.
export function demoCtxForWidget(id, cellW, cellH) {
  const base = { cellW, cellH, units: 'F', cfg: {} };
  switch (id) {
    case 'weather':
      // One demo payload for both views — the merged widget's variant rides
      // in on the caller's settings, so this must not pin one.
      return { ...base, weather: DEMO_WEATHER,
        settings: { lat: 0, lon: 0, stats: ['feels','humid','wind','cloud'] } };
    case 'calendar':
      return { ...base, events: DEMO_EVENTS,
        settings: { icalUrls: ['demo'] } };
    case 'codeactivity':
      return { ...base, codeActivity: DEMO_CODE_ACTIVITY,
        settings: { username: 'octocat' } };
    case 'ai':
      // Frozen so the widgets-matrix render stays byte-identical — the whole
      // point of demo data is that a screenshot diff means a real change.
      return { ...base,
        ai: { text: 'Cool and clear this morning, high near 78. Two meetings before noon, nothing after 3.', at: base.now - 3 * 3600 * 1000 },
        settings: { prompt: 'Brief me on today.', cadence: 'daily' } };

    case 'webhook':
      return { ...base,
        webhook: { data: { steps: 8432, goal: 10000, note: 'Morning run done' },
                   at: Date.now() - 5 * 60000 },
        settings: { key: 'demo' } };
    case 'photo':
      // Reuse the frozen 1-bit demo artwork so the pool card shows a real
      // dithered image instead of the "Add a photo" placeholder.
      return { ...base,
        photo: { src: `data:image/png;base64,${DEMO_ARTWORK_B64}` },
        settings: { variant: 'framed', caption: 'Sunday market', title: 'PHOTO' } };
    case 'eink_battery': {
      const t0 = Date.now() - 12 * 3600 * 1000;
      const pcts = [98, 95, 91, 88, 84, 80, 76, 73, 69, 66, 62, 82];
      return { ...base,
        battery: { v: 4.03, pct: 82, at: Date.now() - 5 * 60 * 1000 },
        batteryHistory: pcts.map((pct, i) => ({ pct, v: 3.4 + (pct / 100) * 0.8, at: t0 + i * 3600 * 1000 })),
        settings: {} };
    }
    case 'clock':
      // Local view needs clockNow; the two zone views render from settings
      // and a frozen `now`. The matrix draws all three, so supply both.
      return { ...base,
        now: Date.UTC(2026, 5, 1, 16, 20, 0),
        clockNow: DEMO_CLOCK,
        settings: { zones: ['LONDON|Europe/London', 'TOKYO|Asia/Tokyo', 'NEW YORK|America/New_York'], format: '12h' } };
    case 'sparkline': {
      // Show the weather-temperature trend in the pool so the card reads as
      // a general metric chart, not a battery-only sparkline. A believable
      // daytime warm-up-then-cool hourly curve.
      const temps = [74, 75, 77, 80, 83, 86, 88, 90, 91, 90, 88, 85, 82, 80, 78, 77];
      return { ...base,
        weather: { hourly: temps.map((temp, i) => ({ label: `${i}`, temp, precip: 10 })) },
        settings: { source: 'weather_temp', title: 'TEMPERATURE' } };
    }
    case 'markets':
      // One of each kind, so the pool card shows what the tile is FOR: a
      // stock, a coin and a currency pair in one list.
      return { ...base,
        markets: {
          vs: 'usd',
          rows: [
            { label: 'AAPL',    value: 227.52,   change: 0.8,  kind: 'stock' },
            { label: 'BTC',     value: 64213,    change: -1.4, kind: 'crypto' },
            { label: 'EUR/USD', value: 1.0842,   change: null, kind: 'fx' },
          ],
          stale: false
        },
        settings: {} };
    case 'outdoors':
      // One widget, three views, and the matrix renders every variant — so
      // all three need data or two of the three snapshots would be
      // placeholders.
      return { ...base,
        sun: { sunrise: Date.UTC(2026, 5, 1, 9, 34), sunset: Date.UTC(2026, 5, 1, 23, 58),
               daylightSec: 51840, stale: false },
        uv: { uv: 7.4, uvMax: 9.2 },
        aqi: DEMO_AQI,
        settings: {} };
    case 'tasks':
      return { ...base, tasks: {
        items: [
          { title: 'Submit expense report', due: 'today', priority: 1 },
          { title: 'Call the dentist', due: 'TOMORROW', priority: 4 },
          { title: 'Review Q3 roadmap', due: 'THU', priority: 2 },
          { title: 'Water the plants', due: '', priority: 4 },
          { title: 'Renew domain', due: 'overdue', priority: 1 },
          { title: 'Book flights', due: 'JUL 12', priority: 3 }
        ], stale: false
      }, settings: { source: 'todoist' } };
    case 'transit':
      return { ...base, transit: {
        stop: 'L06N',
        items: [
          { line: 'L', minutes: 2 },
          { line: 'L', minutes: 7 },
          { line: 'L', minutes: 12 },
          { line: 'L', minutes: 18 },
          { line: 'L', minutes: 24 }
        ], stale: false
      }, settings: { line: 'L', direction: 'N' } };
    case 'headlines':
      return { ...base, headlines: {
        source: 'Hacker News',
        items: [
          { title: 'Show HN: I built an e-ink dashboard that runs for months', age: '1h' },
          { title: 'The quiet comeback of RSS', age: '3h' },
          { title: 'A deep dive into Floyd–Steinberg dithering', age: '5h' },
          { title: 'Why 1-bit displays are having a moment', age: '7h' },
          { title: 'Ask HN: favorite low-power side projects?', age: '9h' },
          { title: 'Building a paper-like reading device from scratch', age: '11h' }
        ], stale: false
      }, settings: { source: 'hn' } };
    case 'daily':
      // Frozen now → a fixed day-of-year → the same built-in quote and word
      // every run, which is what makes the matrix deterministic.
      return { ...base, now: Date.UTC(2026, 5, 1, 12, 0, 0), onThisDay: {
        dateLabel: 'JUNE 16',
        events: [
          { year: 1963, text: 'Valentina Tereshkova becomes the first woman in space aboard Vostok 6.' },
          { year: 1884, text: 'The first purpose-built roller coaster in America opens at Coney Island.' },
          { year: 1779, text: 'Spain declares war on the Kingdom of Great Britain.' },
          { year: 2016, text: 'Shanghai Disneyland, the first Disney park in mainland China, opens.' },
          { year: 1903, text: 'The Ford Motor Company is incorporated.' },
          { year: 1846, text: 'The Bear Flag Revolt begins in California.' }
        ], stale: false
      }, settings: {} };

    case 'qr':
      // The matrix used to render qr's SETUP placeholder, because
      // def.defaults() ships an empty `data` — which is how a QR that
      // flattened to a blank white square on the default inverted theme got
      // all the way to a panel without a single guard noticing (2026-09-17).
      // A frozen payload puts the actual artwork under test:visual.
      return { ...base, settings: {
        variant: 'caption', mode: 'url', level: 'M',
        data: 'https://example.com/matrix', caption: 'SCAN ME', title: 'QR'
      } };

    case 'chess': {
      // Same reasoning as qr: without a frozen puzzle the matrix only ever
      // saw "Puzzle unavailable", so the board's two-tone artwork was never
      // compared. Legal position, fixed, no fetch.
      const rank = (spec) => spec.split(',').map(c => (c === '.' ? null : c));
      return { ...base, chessPuzzle: {
        board: [
          rank('.,.,.,.,.,.,bk,.'),
          rank('.,.,.,.,.,bp,bp,bp'),
          rank('.,.,.,.,.,.,.,.'),
          rank('.,.,.,.,.,.,.,.'),
          rank('.,.,.,.,.,.,.,.'),
          rank('.,.,.,.,.,.,.,.'),
          rank('.,.,.,.,.,wp,wp,wp'),
          rank('.,.,.,.,.,.,wk,.'),
        ],
        turn: 'w', rating: 1700, themes: ['endgame'], stale: false
      }, settings: {} };
    }

    case 'moon':
      // Frozen now ≈ 8 days into the cycle → a clean first-quarter disc
      // (~58% lit, waxing) for the matrix / visual-regression.
      return { ...base, now: Date.UTC(2000, 0, 6, 18, 14, 0) + 8 * 86400000, settings: {} };
    case 'countdown':
      // Frozen now + target → deterministic "12 DAYS" in the matrix /
      // visual-regression. now is a fixed epoch, target 12d 6h later.
      return {
        ...base,
        now: Date.UTC(2026, 5, 1, 0, 0, 0),
        settings: { target: '2026-06-13T06:00', label: 'until launch' }
      };
    case 'text':
      // Tokens are resolved server-side, so the palette can't run them
      // here. Pre-resolve to a believable headline + subtitle so the
      // pool card reads as a configured text widget rather than the
      // empty "CLICK TO SET UP" outline.
      return { ...base, resolvedText: {
        text: 'Brooklyn · Saturday, June 6',
        subtitle: 'refreshed 12m ago'
      }, settings: { variant: 'bar', align: 'left', upper: true, fontFamily: 'sans' } };
    default:
      return { ...base, settings: {} };
  }
}
