// Demo data used by the widget pool / hover-card preview. Each
// pool tile renders with this instead of the live config so users see
// what a fully-configured widget will look like, not the
// SETUP NEEDED placeholder. The numbers/copy are deliberately
// generic ("Coffee with Lia", AAPL, partly cloudy 82°F) so nothing
// reads like a real user's data — and they're frozen, not derived
// from the current date, so the pool preview is reproducible.

export const DEMO_WEATHER = {
  temp: 82, feelsLike: 86, tempMin: 68, tempMax: 90,
  humidity: 64,
  windSpeed: 7, windGust: 11, windDir: 'NW', windUnit: 'mph',
  cloudCover: 38,
  desc: 'PARTLY CLOUDY', main: 'Clouds',
  sunrise: '6:24',  sunset:  '8:22',
  sunriseMin: 384,  sunsetMin: 1222,  nowMin: 700,
  forecast: [
    { name: 'MON', hi: 82, lo: 68, main: 'Clouds', precip: 20 },
    { name: 'TUE', hi: 79, lo: 67, main: 'Rain',   precip: 70 },
    { name: 'WED', hi: 77, lo: 65, main: 'Rain',   precip: 80 },
    { name: 'THU', hi: 80, lo: 66, main: 'Clear',  precip:  5 },
    { name: 'FRI', hi: 84, lo: 69, main: 'Clear',  precip:  0 },
    { name: 'SAT', hi: 88, lo: 71, main: 'Clouds', precip: 15 },
    { name: 'SUN', hi: 85, lo: 70, main: 'Clouds', precip: 30 }
  ],
  hourly: [
    { label: '9P',  temp: 78, main: 'Clear', precip:  5 },
    { label: '10P', temp: 76, main: 'Clear', precip:  5 },
    { label: '11P', temp: 74, main: 'Clear', precip:  5 },
    { label: '12A', temp: 72, main: 'Clouds', precip: 10 },
    { label: '1A',  temp: 71, main: 'Clouds', precip: 15 },
    { label: '2A',  temp: 70, main: 'Rain',   precip: 60 }
  ],
  stale: false,
  units: 'F'
};

export const DEMO_EVENTS = [
  { title: 'Coffee with Lia',       dayLabel: 'MON', startLabel: '9:00 AM',  section: 'TODAY' },
  { title: 'Brand workshop',        dayLabel: 'MON', startLabel: '12:30 PM', section: 'TODAY' },
  { title: 'Standup',               dayLabel: 'TUE', startLabel: '10:00 AM', section: 'LATER' },
  { title: 'Dentist',               dayLabel: 'WED', startLabel: '3:00 PM',  section: 'LATER' },
  { title: 'Yoga',                  dayLabel: 'THU', startLabel: '7:00 AM',  section: 'LATER' },
  { title: "Mom's birthday",        dayLabel: 'FRI', startLabel: 'all day',  section: 'LATER', isAllDay: true },
  { title: 'Dinner · 11 Madison',   dayLabel: 'SAT', startLabel: '7:30 PM',  section: 'LATER' },
  { title: 'Market run',            dayLabel: 'SUN', startLabel: '11:00 AM', section: 'LATER' }
];


// Placeholder album art: 160×160 PNG, nested rotated-diamond pattern.
// Survives the 1-bit threshold (pure black/white only, no gray) so it
// reads cleanly at any popup scale. Generated by a sharp pipeline in
// the pool-demo helper; embedded here as a base64 string so the pool
// doesn't need to make a network call to populate the preview.
const DEMO_ARTWORK_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAKAAAACgAQMAAACxAfVuAAAABlBMVEX///8AAABVwtN+AAAACXBIWXMAAAPoAAAD6AG1e1JrAAACSklEQVR4nL3XTbKrIBCG4aYYMGQJLIWlmaW5FJfA0EHKPtX8GIV3eOs6ExN5ok3zReT/Hx8YczsM+gMGQ4HBeMJg+sJgvmBwUxhUXaFOdYV61RUaVFdoVF2hSXWFZtUVuqmuUNUV6mxwX5krNNhgWZnbAk165QWa9ZsW6KZnXKCqJcxQp3r4GWoDdmFmfuwWM7NOJhOzsmRi9iuPo34zTlDV4vYJahq3T1A7DWWC2hdDmaA2RTwnqGHyNUHtLF8T1L636QS1GWwufUArU/UNtROrT/eEVma7RXkzrT63B9QotT7zA1qZVp/pAW3Mdo+Jub2gjXnlF7Qxv+kFbcwzvqCNWcIL2piHf0Ebc3cvaGNaLckP2ph28XNDO9Nus9/QzrQJjxvamUYrN7QzpV4Z0MF8QTvT19kGtDNrLcmAdmatpU+HDmZqN2nQway1dHToYNZaKh06mPe1c9TmqKWrQwdzzKfXgzlkqn0J/Wppr9DBrGWTO7QuoV8tlQr9MW9a4U86uqfQ7ILOTL8o0W+P9JQCPU9PT97ROxJ6m4LvPVOFJKqlSFUXqD49VbKjmhdaHYLrKNOKS7Q2I63iQOvdU2dw1EOEuo1gX8rUwRL1ukhdMVD/9NRpHfVkoe4t2Ocz7QiJ9o5Iu0yg/cjTzuVojxPaDQX3zUw7bKK9ONKuHWh/95QEHGUGoXQhmEMyJZZE2SZSCgqUlzwlK0cZTCitCea6TAkwUVaMlCoD5U9PSdVRphVKv4I5GRM1Zm9M6ZjnMfnjfwT8N/Hvjj/llOftknBIkAAAAABJRU5ErkJggg==';

export const DEMO_NOWPLAYING = {
  title: 'Empty Seats',
  artist: 'Crumb',
  album: 'Pioneer Works',
  isPlaying: true,
  durationSec: 217,
  elapsedSec: 84,
  sourceLabel: 'SPOTIFY',
  artworkBase64: DEMO_ARTWORK_B64
};

export const DEMO_BATTERY = { percent: 87, state: 'charging' };

export const DEMO_AQI = {
  aqi: 42, band: 0, bands: 6, label: 'GOOD',
  pm25: 9, pm10: 17, o3: 31, no2: 8, stale: false
};


export const DEMO_CLOCK = {
  timeStr: '9:18',
  ampm: 'PM',
  dateLine: 'FRI MAY 31',
  style: 'big'
};

// Returns a render context for the given widget id with demo data
// plumbed into the slots the widget expects. cellW + cellH come from
// the size the pool is rendering at so widgets that branch on tier
// (forecast day count, hi-tier-only hourly strip, etc.) render at
// the size's actual fidelity.
export function demoCtxForWidget(id, cellW, cellH) {
  const base = { cellW, cellH, units: 'F', cfg: {} };
  switch (id) {
    case 'weather_hero':
      return { ...base, weather: DEMO_WEATHER,
        settings: { lat: 0, lon: 0, stats: ['feels','humid','wind','cloud'] } };
    case 'weather_forecast':
      return { ...base, weather: DEMO_WEATHER,
        settings: { lat: 0, lon: 0 } };
    case 'calendar':
      return { ...base, events: DEMO_EVENTS,
        settings: { icalUrls: ['demo'] } };
    case 'mac_nowplaying':
      return { ...base, macNowPlaying: DEMO_NOWPLAYING, settings: {} };
    case 'mac_battery':
      return { ...base, macBattery: DEMO_BATTERY, settings: {} };
    case 'eink_battery':
      return { ...base,
        battery: { v: 4.03, pct: 82, at: Date.now() - 5 * 60 * 1000 },
        settings: {} };
    case 'clock':
      return { ...base, clockNow: DEMO_CLOCK, settings: {} };
    case 'aqi':
      return { ...base, aqi: DEMO_AQI, settings: {} };
    case 'onthisday':
      return { ...base, onThisDay: {
        dateLabel: 'JUNE 16',
        events: [
          { year: 1963, text: 'Valentina Tereshkova becomes the first woman in space aboard Vostok 6.' },
          { year: 1884, text: 'The first purpose-built roller coaster in America opens at Coney Island.' },
          { year: 1779, text: 'Spain declares war on the Kingdom of Great Britain.' },
          { year: 2016, text: 'Shanghai Disneyland, the first Disney park in mainland China, opens.' },
          { year: 1903, text: 'The Ford Motor Company is incorporated.' },
          { year: 1846, text: 'The Bear Flag Revolt begins in California.' }
        ], stale: false
      }, settings: {} };
    case 'quote':
      // Frozen now → a fixed day-of-year → deterministic built-in quote.
      return { ...base, now: Date.UTC(2026, 5, 1, 12, 0, 0), settings: {} };
    case 'world_clock':
      // Frozen now → deterministic times across zones for the matrix.
      return {
        ...base,
        now: Date.UTC(2026, 5, 1, 16, 20, 0),
        settings: { zones: ['LONDON|Europe/London', 'TOKYO|Asia/Tokyo', 'NEW YORK|America/New_York'], format: '12h' }
      };
    case 'moon':
      // Frozen now ≈ 8 days into the cycle → a clean first-quarter disc
      // (~58% lit, waxing) for the matrix / visual-regression.
      return { ...base, now: Date.UTC(2000, 0, 6, 18, 14, 0) + 8 * 86400000, settings: {} };
    case 'countdown':
      // Frozen now + target → deterministic "12 DAYS" in the matrix /
      // visual-regression. now is a fixed epoch, target 12d 6h later.
      return {
        ...base,
        now: Date.UTC(2026, 5, 1, 0, 0, 0),
        settings: { target: '2026-06-13T06:00', label: 'until launch' }
      };
    case 'text':
      // Tokens are resolved server-side, so the palette can't run them
      // here. Pre-resolve to a believable headline + subtitle so the
      // pool card reads as a configured text widget rather than the
      // empty "CLICK TO SET UP" outline.
      return { ...base, resolvedText: {
        text: 'Brooklyn · Saturday, June 6',
        subtitle: 'refreshed 12m ago'
      }, settings: { variant: 'bar', align: 'left', upper: true, fontFamily: 'sans' } };
    default:
      return { ...base, settings: {} };
  }
}
